### PR TITLE
Extend distributions and modules documentation

### PR DESCRIPTION
**Pull request by nichtich**
Please have a look at this extension of Catmandu website with another page `distributions.html`. It includes a list of all Catmandu distributions from CPAN with additional information and lists of fixes, stores, importers, exporters. The information can further be extended once https://github.com/LibreCat/Catmandu/pull/148 has been released so we can show abstract and configuration of each fix/store/importer/exporter. The current `distributions.fix` also fetches information about Debian packes, we could add other operating systems as well.

### CODE REVIEW

**Comment by phochste** [comment]
Uploaded.

Can you explain a bit which commands need to be run each night to update this?

Is this a correct script?

    make local
    make
    git commit -m "autoupdate" distributions.html  >> ${LOG} 2>&1
    git push  >> ${LOG} 2>&1

There are no new files that need to be added to github? Just touching distributions.html?

**Comment by nichtich** [comment]
I added documentation in `README.md` and extended the Makefile (#11).

**Comment by phochste** [comment]
Thx! Added to the cron scripts.

**Comment by nichtich** [comment]
The number of passing/failing tests will likely trigger an update each day. If this is a problem we could map the test values for instance to more fuzzy values (e.g. log10 => "none","some","several","many") as the total numbers are not that relevant anyway.

**Pull request merged**
